routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){

    Route::get('/',function(){
        return redirect('login');
    });

    Route::get('login','UserAuthController@login')->name('login');
    Route::post('login','UserAuthController@do_login')->name('do_login');

    Route::get('forget/password','UserAuthController@forget_password')->name('forget_password');
    Route::post('forget/password','UserAuthController@forget_password_post')->name('forget_password_post');

    Route::get('reset/password/{token}','UserAuthController@reset_password')->name('reset_password');
    Route::post('reset/password/{token}','UserAuthController@reset_password_final')->name('reset_password_final');

    Route::group(['middleware'=>'auth'],function(){

        Route::group(['prefix'=>'dashboard'],function(){
            Route::get('/',function(){
                return view('admin.index',['title'=>trans('admin.Admin Panel')]);
            });


            Route::resource('users','UserController');
            Route::get('users/delete/{id}','UserController@destroy')->name('user_delete');

            Route::resource('categories','CategoryController');
            Route::get('categories/delete/{id}','CategoryController@destroy')->name('category_delete');


            Route::resource('products','ProductController');
            Route::get('products/delete/{id}','ProductController@destroy')->name('product_delete');

            Route::resource('clients','ClientController');
            Route::get('clients/delete/{id}','ClientController@destroy')->name('client_delete');

            Route::resource('clients.orders','OrderController');
            Route::get('clients.orders/delete/{id}','OrderController@destroy')->name('order_delete');

            Route::resource('orders','OrdersController');
            Route::get('orders/{order}/products','OrdersController@products')->name('orders.products');


            Route::any('logout','UserAuthController@logout')->name('logout');
        });
    });

});

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    use HasFactory;
    protected $table = 'clients';
    protected $guarded = [];
    protected $casts = ['phone'=>'array'];

    public function orders(){
        return $this->hasMany(Order::class);
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Models\Client;
use Illuminate\Http\Request;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = Client::all();
        return view('admin.clients.index',['title'=>trans('admin.Clients List'),'clients'=>$clients]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.clients.create',['title'=>trans('admin.Add Client')]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
//        dd($request);
        $data = $request->validate([
            'name'=>'required',
            'address'=>'required',
            'phone'=>'required|array|min:1',
            'phone.0'=>'required',
        ]);
        Client::create($data);
        session()->flash('success',trans('admin.Data Added Successfully'));
        return redirect(aurl('clients'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $client = Client::find($id);
        return view('admin.clients.edit',['title'=>trans('admin.Client Edit'),'client'=>$client]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->validate([
            'name'=>'required',
            'address'=>'required',
            'phone'=>'required|array|min:1',
            'phone.0'=>'required',
        ]);
        Client::where('id',$id)->update($data);
        session()->flash('success',trans('admin.Data Updated Successfully'));
        return redirect(aurl('clients'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $client = Client::find($id);
        $client->delete();
        session()->flash('success',trans('admin.Data Deleted Successfully'));
        return redirect(aurl('clients'));
    }
}

resources/views/admin/clients/create.blade.php
@extends('admin.home')
@section('content')

    <div class="row layout-top-spacing">
        <div class="col-lg-12 col-12  layout-spacing">
            @include('admin.layout.message')
            <div id="tabsIcons" class="col-lg-12 col-12 layout-spacing">
                <div class="statbox widget box box-shadow">
                    <div class="widget-header">
                        <div class="row">
                            <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                                <h4>{{$title}}</h4>
                            </div>
                        </div>
                    </div>
                    <div class="widget-content  icon-tab">
                        <form method="post" action="{{route('clients.store')}}">
                            {{csrf_field()}}

                            <div class="form-group row  mb-4">
                                <label for="name" class="col-sm-3 col-form-label col-form-label-sm">{{trans('admin.Name')}}</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control form-control-sm" id="name" placeholder="{{trans('admin.Name')}}" name="name" value="{{old('name')}}">
                                </div>
                            </div>


                            <div class="form-group row  mb-4">
                                <label for="address" class="col-sm-3 col-form-label col-form-label-sm">{{trans('admin.Address')}}</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control form-control-sm" id="address" placeholder="{{trans('admin.Address')}}" name="address" value="{{old('address')}}">
                                </div>
                            </div>


                            @for($i=0;$i<2;$i++)
                                <div class="form-group row  mb-4">
                                    <label for="phone" class="col-sm-3 col-form-label col-form-label-sm">{{trans('admin.Phone')}}</label>
                                    <div class="col-sm-9">
                                        <input type="text" class="form-control form-control-sm" id="phone" placeholder="{{trans('admin.Phone')}}" name="phone[]" >
                                    </div>
                                </div>
                            @endfor


                            <div class="form-group">

                                <button type="submit" class="btn btn-primary">{{trans('admin.Save')}}</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>


    </div>
@endsection

resources/views/admin/clients/edit.blade.php
@extends('admin.home')
@section('content')

    <div class="row layout-top-spacing">
        <div class="col-lg-12 col-12  layout-spacing">
            @include('admin.layout.message')
            <div id="tabsIcons" class="col-lg-12 col-12 layout-spacing">
                <div class="statbox widget box box-shadow">
                    <div class="widget-header">
                        <div class="row">
                            <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                                <h4>{{$title}}</h4>
                            </div>
                        </div>
                    </div>
                    <div class="widget-content  icon-tab">
                        <form method="post" action="{{route('clients.update',$client->id)}}" >
                            {{csrf_field()}}
                            <input type="hidden" name="_method" value="put">
                            <div class="form-group row  mb-4">
                                <label for="name" class="col-sm-3 col-form-label col-form-label-sm">{{trans('admin.Name')}}</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control form-control-sm" id="name" placeholder="{{trans('admin.Name')}}" name="name" value="{{$client->name}}">
                                </div>
                            </div>


                            <div class="form-group row  mb-4">
                                <label for="address" class="col-sm-3 col-form-label col-form-label-sm">{{trans('admin.Address')}}</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control form-control-sm" id="address" placeholder="{{trans('admin.Address')}}" name="address" value="{{$client->address}}">
                                </div>
                            </div>


                            @for($i=0;$i<2;$i++)
                                <div class="form-group row  mb-4">
                                    <label for="phone" class="col-sm-3 col-form-label col-form-label-sm">{{trans('admin.Phone')}}</label>
                                    <div class="col-sm-9">
                                        <input type="text" class="form-control form-control-sm" id="phone" placeholder="{{trans('admin.Phone')}}" name="phone[]" value="{{$client->phone[$i]}}">
                                    </div>
                                </div>
                            @endfor
                            <div class="form-group">

                                <button type="submit" class="btn btn-primary">{{trans('admin.Update')}}</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>


    </div>
@endsection

resources/views/admin/clients/index.blade.php
@extends('admin.home')
@push('css')
    <link href="{{url('/')}}/admin/plugins/animate/animate.css" rel="stylesheet" type="text/css" />
    <script src="{{url('/')}}/admin/plugins/sweetalerts/promise-polyfill.js"></script>
    <link href="{{url('/')}}/admin/plugins/sweetalerts/sweetalert2.min.css" rel="stylesheet" type="text/css" />
    <link href="{{url('/')}}/admin/plugins/sweetalerts/sweetalert.css" rel="stylesheet" type="text/css" />
    <link href="{{url('/')}}/admin/assets/css/components/custom-sweetalert.css" rel="stylesheet" type="text/css" />
@endpush
@section('content')
    <div class="row layout-top-spacing">
        @include('admin.layout.message')
        <div class="col-xl-12 col-lg-12 col-sm-12  layout-spacing">
            <div class="widget-content widget-content-area br-6">
                <table id="html5-extension" class="table table-hover non-hover" style="width:100%">
                    <thead>
                    <tr>
                        <th>{{trans('admin.ID')}}</th>
                        <th>{{trans('admin.Name')}}</th>
                        <th>{{trans('admin.Address')}}</th>
                        <th>{{trans('admin.Phone')}}</th>
                        <th>{{trans('admin.Add Order')}}</th>
                        <th class="dt-no-sorting">{{trans('admin.Action')}}</th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach($clients as $client)
                            <tr>
                                <td>{{$client->id}}</td>
                                <td>{{$client->name}}</td>
                                <td>{{$client->address}}</td>
                                <td>{{implode(' - ',$client->phone)}}</td>
                                <td>
                                    @if(auth()->user()->hasPermission('create_orders'))

                                        <a href="{{route('clients.orders.create',$client->id)}}" class="btn btn-info">{{trans('admin.Add Order')}}</a> </td>
                                    @else
                                        <a href="" class="btn btn-info disabled">{{trans('admin.Add Order')}}</a> </td>

                                    @endif
                                <td>
                                    @if(auth()->user()->hasPermission('update_clients'))

                                        <a href="{{route('clients.edit',$client->id)}}" class="btn btn-primary">{{trans('admin.Edit')}}</a>
                                    @else
                                        <a href="" class="disabled btn btn-primary">{{trans('admin.Edit')}}</a>
                                    @endif
                                    @if(auth()->user()->hasPermission('delete_clients'))
                                        <a href="{{route('client_delete',$client->id)}}" class="btn btn-danger delbtn">{{trans('admin.Delete')}}</a>
                                    @else
                                        <a href="#" class="btn btn-danger disabled">{{trans('admin.Delete')}}</a>
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>

    </div>
    @push('js')
        <script src="{{url('/')}}/admin/plugins/sweetalerts/sweetalert2.min.js"></script>
        <script src="{{url('/')}}/admin/plugins/sweetalerts/custom-sweetalert.js"></script>
        <script>
            $('.delbtn').on('click', function (e) {
                e.preventDefault();
                var link = $(this).attr('href');
                const swalWithBootstrapButtons = swal.mixin({
                    confirmButtonClass: 'btn btn-success btn-rounded',
                    cancelButtonClass: 'btn btn-danger btn-rounded mr-3',
                    buttonsStyling: false,
                })

                swalWithBootstrapButtons({
                    title: '{{trans('admin.Are you sure?')}}',
                    text: "{{trans('admin.You wont be able to revert this!')}}",
                    type: 'warning',
                    showCancelButton: true,
                    confirmButtonText: '{{trans('admin.Yes, delete it!')}}',
                    cancelButtonText: '{{trans('admin.No, cancel!')}}',
                    reverseButtons: true,
                    padding: '2em'
                }).then(function(result) {
                    if (result.value) {
                        window.location.href = link;
                    } else if (
                        // Read more about handling dismissals
                        result.dismiss === swal.DismissReason.cancel
                    ) {
                        swalWithBootstrapButtons(
                            '{{trans('admin.Cancelled')}}',
                            '{{trans('admin.Your imaginary file is safe :)')}}',
                            'error'
                        )
                    }
                })
            })
        </script>
        <!-- END THEME GLOBAL STYLE -->
    @endpush
@endsection