routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){

    Route::get('/',function(){
        return redirect('login');
    });

    Route::get('login','UserAuthController@login')->name('login');
    Route::post('login','UserAuthController@do_login')->name('do_login');

    Route::get('forget/password','UserAuthController@forget_password')->name('forget_password');
    Route::post('forget/password','UserAuthController@forget_password_post')->name('forget_password_post');

    Route::get('reset/password/{token}','UserAuthController@reset_password')->name('reset_password');
    Route::post('reset/password/{token}','UserAuthController@reset_password_final')->name('reset_password_final');

    Route::group(['middleware'=>'auth'],function(){

        Route::group(['prefix'=>'dashboard'],function(){
            Route::get('/',function(){
                return view('admin.index',['title'=>trans('admin.Admin Panel')]);
            });


            Route::resource('users','UserController');
            Route::get('users/delete/{id}','UserController@destroy')->name('user_delete');

            Route::resource('categories','CategoryController');
            Route::get('categories/delete/{id}','CategoryController@destroy')->name('category_delete');


            Route::resource('products','ProductController');
            Route::get('products/delete/{id}','ProductController@destroy')->name('product_delete');

            Route::resource('clients','ClientController');
            Route::get('clients/delete/{id}','ClientController@destroy')->name('client_delete');

            Route::resource('clients.orders','OrderController');
            Route::get('clients.orders/delete/{id}','OrderController@destroy')->name('order_delete');

            Route::resource('orders','OrdersController');
            Route::get('orders/{order}/products','OrdersController@products')->name('orders.products');


            Route::any('logout','UserAuthController@logout')->name('logout');
        });
    });

});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
class Product extends Model implements TranslatableContract
{
    use HasFactory,Translatable;
    protected $guarded=[];
    protected $table = 'products';
    public $translatedAttributes = ['name','description'];

    public function category(){
        return $this->belongsTo(Category::class);
    }

    protected $appends = ['image_path','profit_percent'];
    public function getImagePathAttribute(){
        return asset('uploads/products/'.$this->image);
    }

    public function getProfitPercentAttribute(){
        $profit = $this->sale_price - $this->purchase_price;
        $profit_precent = $profit * 100 / $this->purchase_price;
        return number_format($profit_precent,2);
    }

    public function orders(){
        return $this->belongsToMany(Order::class,'product_order');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\Rule;
use Intervention\Image\Facades\Image;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        $category = Category::all();
        return view('admin.product.index',['title'=>trans('admin.Products List'),'products'=>$products,'categories'=>$category]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('admin.product.create',['title'=>trans('admin.Add Product'),'categories'=>$categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'category_id'=>'required|exists:category_translations,id',
            'purchase_price'=>'required',
            'sale_price'=>'required',
            'stock'=>'required',
            'image'=>'image',
        ];
        foreach(config('translatable.locales') as $local){
            $rules+=[$local.'.name'=>'required|unique:product_translations,name'];
            $rules+=[$local.'.description'=>'required'];
        }

        $data = $request->validate($rules);
        if($request->image){
            Image::make($request->image)->resize(300,null,function($constraint){
                $constraint->aspectRatio();
            })->save(public_path('uploads/products/'.$request->image->hashName()));

            $data['image'] = $request->image->hashName();
        }
        Product::create($data);
        session()->flash('success',trans('admin.Data Added Successfully'));
        return redirect(aurl('products'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);
        $categories = Category::all();
        return view('admin.product.edit',['title'=>trans('admin.Product Edit'),'product'=>$product,'categories'=>$categories]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::find($id);
        $rules = [
            'category_id'=>'required|exists:category_translations,id',
            'purchase_price'=>'required',
            'sale_price'=>'required',
            'stock'=>'required',
            'image'=>'image',
        ];
        foreach(config('translatable.locales') as $local){
            $rules+=[$local.'.name'=>['required',Rule::unique('product_translations','name')->ignore($id,'product_id')]];
            $rules+=[$local.'.description'=>'required'];
        }

        $data = $request->validate($rules);
        if($request->image){
            if($product->image != 'default.png'){
                Storage::disk('public_uploads')->delete('products/'.$product->image);
            }
            Image::make($request->image)->resize(300,null,function($constraint){
                $constraint->aspectRatio();
            })->save(public_path('uploads/products/'.$request->image->hashName()));

            $data['image'] = $request->image->hashName();
        }
        $product->update($data);
        session()->flash('success',trans('admin.Data Updated Successfully'));
        return redirect(aurl('products'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::find($id);
        if($product->image !='default.png'){
            Storage::disk('public_uploads')->delete('products/'.$product->image);
        }
        $product->delete();
        session()->flash('success',trans('admin.Data Deleted Successfully'));
        return redirect(aurl('products'));
    }
}

resources/views/admin/product/create.blade.php
@extends('admin.home')
@push('css')
    <!--  BEGIN CUSTOM STYLE FILE  -->
    <link href="{{url('/')}}/admin/assets/css/scrollspyNav.css" rel="stylesheet" type="text/css" />
    <link href="{{url('/')}}/admin/assets/css/components/tabs-accordian/custom-tabs.css" rel="stylesheet" type="text/css" />
@endpush
@section('content')

    <div class="row layout-top-spacing">
        <div class="col-lg-12 col-12  layout-spacing">
            @include('admin.layout.message')
            <div id="tabsIcons" class="col-lg-12 col-12 layout-spacing">
                <div class="statbox widget box box-shadow">
                    <div class="widget-header">
                        <div class="row">
                            <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                                <h4>{{$title}}</h4>
                            </div>
                        </div>
                    </div>
                    <div class="widget-content  icon-tab">
                        <form method="post" action="{{route('products.store')}}" enctype="multipart/form-data">
                            {{csrf_field()}}

                            <div class="form-group row mb-4">
                                <label for="categories" class="col-sm-3 col-form-label col-form-label-sm">{{trans('admin.Categories')}}</label>

                                <div class="col-sm-9">
                                    <select class="form-control form-control-lg" name="category_id">
                                        <option>{{trans('admin.Categories')}}</option>
                                        @foreach($categories as $category)
                                            <option value="{{$category->id}}" {{old('category_id') == $category->id ? 'selected':''}}>{{$category->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            @foreach(config('translatable.locales') as $local)
                                <div class="form-group row  mb-4">
                                    <label for="name_ar" class="col-sm-3 col-form-label col-form-label-sm">{{trans('admin.'.$local.'.name')}}</label>
                                    <div class="col-sm-9">
                                        <input type="text" class="form-control form-control-sm" id="name_ar" placeholder="{{trans('admin.'.$local.'.name')}}" name="{{$local}}[name]" value="{{old($local.'.name')}}">
                                    </div>
                                </div>

                                <div class="form-group row  mb-4">
                                    <label for="description" class="col-sm-3 col-form-label col-form-label-sm">{{trans('admin.'.$local.'.description')}}</label>
                                    <div class="col-sm-9">
                                        <textarea class="form-control" id="description" rows="3" name="{{$local}}[description]">{{old($local.'.description')}}</textarea>
                                    </div>
                                </div>
                            @endforeach

                            <div class="form-group row mb-4">
                                <label for="sale_price" class="col-sm-3 col-form-label col-form-label-lg">{{trans('admin.Sale Price')}}</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control form-control-sm" id="sale_price" name="sale_price" placeholder="{{trans('admin.Sale Price')}}" value="{{old('sale_price')}}">
                                </div>
                            </div>

                            <div class="form-group row mb-4">
                                <label for="purchase_price" class="col-sm-3 col-form-label col-form-label-lg">{{trans('admin.Purchase Price')}}</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control form-control-sm" id="purchase_price" name="purchase_price" placeholder="{{trans('admin.Purchase Price')}}" value="{{old('purchase_price')}}">
                                </div>
                            </div>

                            <div class="form-group row mb-4">
                                <label for="stock" class="col-sm-3 col-form-label col-form-label-lg">{{trans('admin.Stock')}}</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control form-control-sm" id="stock" name="stock" placeholder="{{trans('admin.Stock')}}" value="{{old('stock')}}">
                                </div>
                            </div>




                            <div class="form-group row mb-4">
                                <label for="image" class="col-sm-3 col-form-label col-form-label-lg">{{trans('admin.Image')}}</label>
                                <div class="col-sm-9">
                                    <input type="file" class="form-control-file image" id="image" name="image">
                                </div>
                            </div>

                            <div class="form-group row mb-4">
                                <label for="image" class="col-sm-3 col-form-label col-form-label-lg">{{trans('admin.Image Preview')}}</label>
                                <div class="col-sm-9">
                                    <img src="{{asset('uploads/products/default.png')}}" width="100px" height="100px" class="img-thumbnail img-preview">
                                </div>
                            </div>

                            <div class="form-group">

                                <button type="submit" class="btn btn-primary">{{trans('admin.Save')}}</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>


    </div>




    @push('js')
        <script src="{{url('/')}}/admin/assets/js/scrollspyNav.js"></script>
        <script>
            $(".image").change(function() {
                if (this.files && this.files[0]) {
                    var reader = new FileReader();

                    reader.onload = function(e) {
                        $('.img-preview').attr('src', e.target.result);
                    }

                    reader.readAsDataURL(this.files[0]); // convert to base64 string
                }
            });
        </script>
    @endpush
@endsection

resources/views/admin/product/edit.blade.php
@extends('admin.home')
@push('css')
    <!--  BEGIN CUSTOM STYLE FILE  -->
    <link href="{{url('/')}}/admin/assets/css/scrollspyNav.css" rel="stylesheet" type="text/css" />
    <link href="{{url('/')}}/admin/assets/css/components/tabs-accordian/custom-tabs.css" rel="stylesheet" type="text/css" />
@endpush
@section('content')

    <div class="row layout-top-spacing">
        <div class="col-lg-12 col-12  layout-spacing">
            @include('admin.layout.message')
            <div id="tabsIcons" class="col-lg-12 col-12 layout-spacing">
                <div class="statbox widget box box-shadow">
                    <div class="widget-header">
                        <div class="row">
                            <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                                <h4>{{$title}}</h4>
                            </div>
                        </div>
                    </div>
                    <div class="widget-content  icon-tab">
                        <form method="post" action="{{route('products.update',$product->id)}}" enctype="multipart/form-data">
                            {{csrf_field()}}

                            <input type="hidden" name="_method" value="put">
                            <div class="form-group row mb-4">
                                <label for="categories" class="col-sm-3 col-form-label col-form-label-sm">{{trans('admin.Categories')}}</label>

                                <div class="col-sm-9">
                                    <select class="form-control form-control-lg" name="category_id">
                                        <option>{{trans('admin.Categories')}}</option>
                                        @foreach($categories as $category)
                                            <option value="{{$category->id}}" {{$product->category_id == $category->id ? 'selected':''}}>{{$category->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            @foreach(config('translatable.locales') as $local)
                                <div class="form-group row  mb-4">
                                    <label for="name_ar" class="col-sm-3 col-form-label col-form-label-sm">{{trans('admin.'.$local.'.name')}}</label>
                                    <div class="col-sm-9">
                                        <input type="text" class="form-control form-control-sm" id="name_ar" placeholder="{{trans('admin.'.$local.'.name')}}" name="{{$local}}[name]" value="{{$product->translate($local)->name}}">
                                    </div>
                                </div>

                                <div class="form-group row  mb-4">
                                    <label for="description" class="col-sm-3 col-form-label col-form-label-sm">{{trans('admin.'.$local.'.description')}}</label>
                                    <div class="col-sm-9">
                                        <textarea class="form-control" id="description" rows="3" name="{{$local}}[description]">{{$product->translate($local)->description}}</textarea>
                                    </div>
                                </div>
                            @endforeach

                            <div class="form-group row mb-4">
                                <label for="sale_price" class="col-sm-3 col-form-label col-form-label-lg">{{trans('admin.Sale Price')}}</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control form-control-sm" id="sale_price" name="sale_price" placeholder="{{trans('admin.Sale Price')}}" value="{{$product->sale_price}}">
                                </div>
                            </div>

                            <div class="form-group row mb-4">
                                <label for="purchase_price" class="col-sm-3 col-form-label col-form-label-lg">{{trans('admin.Purchase Price')}}</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control form-control-sm" id="purchase_price" name="purchase_price" placeholder="{{trans('admin.Purchase Price')}}" value="{{$product->purchase_price}}">
                                </div>
                            </div>

                            <div class="form-group row mb-4">
                                <label for="stock" class="col-sm-3 col-form-label col-form-label-lg">{{trans('admin.Stock')}}</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control form-control-sm" id="stock" name="stock" placeholder="{{trans('admin.Stock')}}" value="{{$product->stock}}">
                                </div>
                            </div>




                            <div class="form-group row mb-4">
                                <label for="image" class="col-sm-3 col-form-label col-form-label-lg">{{trans('admin.Image')}}</label>
                                <div class="col-sm-9">
                                    <input type="file" class="form-control-file image" id="image" name="image">
                                </div>
                            </div>

                            <div class="form-group row mb-4">
                                <label for="image" class="col-sm-3 col-form-label col-form-label-lg">{{trans('admin.Image Preview')}}</label>
                                <div class="col-sm-9">
                                    <img src="{{$product->image_path}}" width="100px" height="100px" class="img-thumbnail img-preview">
                                </div>
                            </div>

                            <div class="form-group">

                                <button type="submit" class="btn btn-primary">{{trans('admin.Save')}}</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>


    </div>




    @push('js')
        <script src="{{url('/')}}/admin/assets/js/scrollspyNav.js"></script>
        <script>
            $(".image").change(function() {
                if (this.files && this.files[0]) {
                    var reader = new FileReader();

                    reader.onload = function(e) {
                        $('.img-preview').attr('src', e.target.result);
                    }

                    reader.readAsDataURL(this.files[0]); // convert to base64 string
                }
            });
        </script>
    @endpush
@endsection

resources/views/admin/product/index.blade.php
@extends('admin.home')
@push('css')
    <link href="{{url('/')}}/admin/plugins/animate/animate.css" rel="stylesheet" type="text/css" />
    <script src="{{url('/')}}/admin/plugins/sweetalerts/promise-polyfill.js"></script>
    <link href="{{url('/')}}/admin/plugins/sweetalerts/sweetalert2.min.css" rel="stylesheet" type="text/css" />
    <link href="{{url('/')}}/admin/plugins/sweetalerts/sweetalert.css" rel="stylesheet" type="text/css" />
    <link href="{{url('/')}}/admin/assets/css/components/custom-sweetalert.css" rel="stylesheet" type="text/css" />
@endpush
@section('content')
    <div class="row layout-top-spacing">
        @include('admin.layout.message')
        <div class="col-xl-12 col-lg-12 col-sm-12  layout-spacing">
            <div class="widget-content widget-content-area br-6">
                <table id="html5-extension" class="table table-hover non-hover" style="width:100%">
                    <thead>
                    <tr>
                        <th>{{trans('admin.ID')}}</th>
                        <th>{{trans('admin.Image')}}</th>
{{--                        <th>{{trans('admin.Category')}}</th>--}}
                        <th>{{trans('admin.Name')}}</th>
                        <th>{{trans('admin.Description')}}</th>
                        <th>{{trans('admin.Purchase Price')}}</th>
                        <th>{{trans('admin.Sale Price')}}</th>
                        <th>{{trans('admin.Profit')}}</th>
                        <th>{{trans('admin.Stock')}}</th>
                        <th>{{trans('admin.Category')}}</th>
                        <th class="dt-no-sorting">{{trans('admin.Action')}}</th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach($products as $product)
                            <tr>
                                <td>{{$product->id}}</td>
                                <td><img src="{{$product->image_path}}" width="50px" height="50px" class="img-thumbnail"> </td>
                                <td>{{$product->name}}</td>
                                <td>{{$product->description}}</td>
                                <td>{{$product->purchase_price}}</td>
                                <td>{{$product->sale_price}}</td>
                                <td>{{$product->profit_percent}}</td>
                                <td>{{$product->stock}}</td>
                                <td>
                                    @foreach($categories as $category)
                                        @if($category->id==$product->category_id)
                                            {{$category->name}}
                                        @endif
                                    @endforeach
                                </td>
                                <td>
                                    @if(auth()->user()->hasPermission('update_products'))

                                        <a href="{{route('products.edit',$product->id)}}" class="btn btn-primary">{{trans('admin.Edit')}}</a>
                                    @else
                                        <a href="" class="disabled btn btn-primary">{{trans('admin.Edit')}}</a>
                                    @endif
                                    @if(auth()->user()->hasPermission('delete_products'))
                                        <a href="{{route('product_delete',$product->id)}}" class="btn btn-danger delbtn">{{trans('admin.Delete')}}</a>
                                    @else
                                        <a href="#" class="btn btn-danger disabled">{{trans('admin.Delete')}}</a>
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>

    </div>
    @push('js')
        <script src="{{url('/')}}/admin/plugins/sweetalerts/sweetalert2.min.js"></script>
        <script src="{{url('/')}}/admin/plugins/sweetalerts/custom-sweetalert.js"></script>
        <script>
            $('.delbtn').on('click', function (e) {
                e.preventDefault();
                var link = $(this).attr('href');
                const swalWithBootstrapButtons = swal.mixin({
                    confirmButtonClass: 'btn btn-success btn-rounded',
                    cancelButtonClass: 'btn btn-danger btn-rounded mr-3',
                    buttonsStyling: false,
                })

                swalWithBootstrapButtons({
                    title: '{{trans('admin.Are you sure?')}}',
                    text: "{{trans('admin.You wont be able to revert this!')}}",
                    type: 'warning',
                    showCancelButton: true,
                    confirmButtonText: '{{trans('admin.Yes, delete it!')}}',
                    cancelButtonText: '{{trans('admin.No, cancel!')}}',
                    reverseButtons: true,
                    padding: '2em'
                }).then(function(result) {
                    if (result.value) {
                        window.location.href = link;
                    } else if (
                        // Read more about handling dismissals
                        result.dismiss === swal.DismissReason.cancel
                    ) {
                        swalWithBootstrapButtons(
                            '{{trans('admin.Cancelled')}}',
                            '{{trans('admin.Your imaginary file is safe :)')}}',
                            'error'
                        )
                    }
                })
            })
        </script>
        <!-- END THEME GLOBAL STYLE -->
    @endpush
@endsection